// @generated by protobuf-ts 2.9.6
// @generated from protobuf file "CharacterType.proto" (syntax proto3)
// tslint:disable
/**
 * @generated from protobuf enum CharacterType
 */
export enum CharacterType {
    /**
     * @generated from protobuf enum value: CHARACTER_TYPE_None = 0;
     */
    None = 0,
    /**
     * @generated from protobuf enum value: CHARACTER_TYPE_PlayerCharacter = 1;
     */
    PlayerCharacter = 1,
    /**
     * @generated from protobuf enum value: CHARACTER_TYPE_Cow = 2;
     */
    Cow = 2
}
