// @generated by protobuf-ts 2.9.6
// @generated from protobuf file "Character.proto" (syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message Character
 */
export interface Character {
    /**
     * @generated from protobuf field: string id = 1;
     */
    id: string;
    /**
     * @generated from protobuf field: bool isMoving = 2;
     */
    isMoving: boolean;
    /**
     * @generated from protobuf field: double x = 3;
     */
    x: number;
    /**
     * @generated from protobuf field: double y = 4;
     */
    y: number;
    /**
     * @generated from protobuf field: uint32 facingDirection = 5;
     */
    facingDirection: number;
}
// @generated message type with reflection information, may provide speed optimized methods
class Character$Type extends MessageType<Character> {
    constructor() {
        super("Character", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "isMoving", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 3, name: "x", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 4, name: "y", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 5, name: "facingDirection", kind: "scalar", T: 13 /*ScalarType.UINT32*/ }
        ]);
    }
    create(value?: PartialMessage<Character>): Character {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        message.isMoving = false;
        message.x = 0;
        message.y = 0;
        message.facingDirection = 0;
        if (value !== undefined)
            reflectionMergePartial<Character>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Character): Character {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* bool isMoving */ 2:
                    message.isMoving = reader.bool();
                    break;
                case /* double x */ 3:
                    message.x = reader.double();
                    break;
                case /* double y */ 4:
                    message.y = reader.double();
                    break;
                case /* uint32 facingDirection */ 5:
                    message.facingDirection = reader.uint32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Character, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* bool isMoving = 2; */
        if (message.isMoving !== false)
            writer.tag(2, WireType.Varint).bool(message.isMoving);
        /* double x = 3; */
        if (message.x !== 0)
            writer.tag(3, WireType.Bit64).double(message.x);
        /* double y = 4; */
        if (message.y !== 0)
            writer.tag(4, WireType.Bit64).double(message.y);
        /* uint32 facingDirection = 5; */
        if (message.facingDirection !== 0)
            writer.tag(5, WireType.Varint).uint32(message.facingDirection);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message Character
 */
export const Character = new Character$Type();
