// @generated by protobuf-ts 2.9.6
// @generated from protobuf file "Move.proto" (syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { Character } from "./Character";
/**
 * @generated from protobuf message Move
 */
export interface Move {
    /**
     * @generated from protobuf field: Character character = 1;
     */
    character?: Character;
    /**
     * @generated from protobuf field: double whenMovingHasChanged = 2;
     */
    whenMovingHasChanged: number;
}
// @generated message type with reflection information, may provide speed optimized methods
class Move$Type extends MessageType<Move> {
    constructor() {
        super("Move", [
            { no: 1, name: "character", kind: "message", T: () => Character },
            { no: 2, name: "whenMovingHasChanged", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ }
        ]);
    }
    create(value?: PartialMessage<Move>): Move {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.whenMovingHasChanged = 0;
        if (value !== undefined)
            reflectionMergePartial<Move>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Move): Move {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* Character character */ 1:
                    message.character = Character.internalBinaryRead(reader, reader.uint32(), options, message.character);
                    break;
                case /* double whenMovingHasChanged */ 2:
                    message.whenMovingHasChanged = reader.double();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Move, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* Character character = 1; */
        if (message.character)
            Character.internalBinaryWrite(message.character, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* double whenMovingHasChanged = 2; */
        if (message.whenMovingHasChanged !== 0)
            writer.tag(2, WireType.Bit64).double(message.whenMovingHasChanged);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message Move
 */
export const Move = new Move$Type();
